// megafunction wizard: %ALTFP_ABS%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTFP_ABS 

// ============================================================
// File Name: ALTFP_ABSa.v
// Megafunction Name(s):
// 			ALTFP_ABS
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 11.0 Build 208 07/03/2011 SP 1 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2011 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altfp_abs CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone II" PIPELINE=0 WIDTH_EXP=8 WIDTH_MAN=23 data result
//VERSION_BEGIN 11.0SP1 cbx_altfp_abs 2011:07:03:21:05:55:SJ cbx_mgl 2011:07:03:21:07:56:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  ALTFP_ABSa_altfp_abs_bs9
	( 
	data,
	result) ;
	input   [31:0]  data;
	output   [31:0]  result;

	wire  [31:0]  data_w;
	wire  gnd_w;

	assign
		data_w = {gnd_w, data[30:0]},
		gnd_w = 1'b0,
		result = data_w;
endmodule //ALTFP_ABSa_altfp_abs_bs9
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module ALTFP_ABSa (
	data,
	result);

	input	[31:0]  data;
	output	[31:0]  result;

	wire [31:0] sub_wire0;
	wire [31:0] result = sub_wire0[31:0];

	ALTFP_ABSa_altfp_abs_bs9	ALTFP_ABSa_altfp_abs_bs9_component (
				.data (data),
				.result (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "UNUSED"
// Retrieval info: CONSTANT: LPM_HINT STRING "UNUSED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altfp_abs"
// Retrieval info: CONSTANT: PIPELINE NUMERIC "0"
// Retrieval info: CONSTANT: WIDTH_EXP NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_MAN NUMERIC "23"
// Retrieval info: USED_PORT: data 0 0 32 0 INPUT NODEFVAL "data[31..0]"
// Retrieval info: CONNECT: @data 0 0 32 0 data 0 0 32 0
// Retrieval info: USED_PORT: result 0 0 32 0 OUTPUT NODEFVAL "result[31..0]"
// Retrieval info: CONNECT: result 0 0 32 0 @result 0 0 32 0
// Retrieval info: GEN_FILE: TYPE_NORMAL ALTFP_ABSa.v TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ALTFP_ABSa.qip TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ALTFP_ABSa.bsf TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ALTFP_ABSa_inst.v TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ALTFP_ABSa_bb.v TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ALTFP_ABSa.inc TRUE TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ALTFP_ABSa.cmp TRUE TRUE
