#!/bin/sh

c:/altera/11.0sp1/quartus//bin/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/ptf_update.pl niosSystemCamControl.ptf 

c:/altera/11.0sp1/quartus//bin/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/mk_systembus.pl --sopc_directory=$sopc_builder --sopc_perl=c:/altera/11.0sp1/quartus//bin/perl --sopc_lib_path="C:/Users/Justin/test1/project/niosControl3CamOnly+C:/Users/Justin/test2/project/niosControl3CamOnly+C:/altera/11.0sp1/ip+c:/altera/11.0sp1/quartus//../ip/altera/sopc_builder_ip+c:/altera/11.0sp1/quartus//../ip/altera/nios2_ip+c:/altera/11.0sp1/quartus//sopc_builder/components" --target_module_name=niosSystemCamControl --system_directory=C:/Users/Justin/test1/project/niosControl3CamOnly --system_name=niosSystemCamControl --project_name=niosControl3CamOnly.qpf --sopc_quartus_dir= $1
